name: Deploy to GMO Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'service-site/package-lock.json'

      - name: Debug - List directories
        run: |
          ls -la
          ls -la service-site || echo "service-site directory not found"

      - name: Install dependencies
        working-directory: service-site
        run: npm ci

      - name: Build project
        working-directory: service-site
        run: npm run build

      - name: Debug - Check build output
        working-directory: service-site
        run: |
          ls -la
          ls -la dist || echo "dist directory not found"

      - name: Debug SSH settings
        run: |
          echo "Checking SSH configuration..."
          echo "SSH_USERNAME is set: ${{ secrets.SSH_USERNAME != '' }}"
          echo "SSH_HOST is set: ${{ secrets.SSH_HOST != '' }}"
          echo "REMOTE_PATH is set: ${{ secrets.REMOTE_PATH != '' }}"
          echo "KNOWN_HOSTS is set: ${{ secrets.KNOWN_HOSTS != '' }}"
          echo "SSH_PRIVATE_KEY is set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
          echo "First few characters of SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY != '' && format('{0}...', secrets.SSH_PRIVATE_KEY, 0, 10) || 'Not provided' }}"

      # 秘密鍵のセットアップを改善
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          # 秘密鍵を安全に保存する
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 鍵の形式とコンテンツを詳細に確認
          echo "Private key file info:"
          file ~/.ssh/id_rsa
          echo "Private key beginning:"
          head -n 3 ~/.ssh/id_rsa
          echo "Private key length in bytes:"
          wc -c ~/.ssh/id_rsa
          
          # known_hostsファイルの設定
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
          # SSH設定を確認
          ls -la ~/.ssh

      # デバッグ用に秘密鍵を修正する追加のステップ（必要な場合）
      - name: Fix SSH key format if needed
        run: |
          # 現在の鍵の先頭を確認
          if ! grep -q "BEGIN" ~/.ssh/id_rsa; then
            echo "SSH key does not have proper header. Attempting to fix..."
            # ヘッダーとフッターを追加
            cp ~/.ssh/id_rsa ~/.ssh/id_rsa.bak
            echo "-----BEGIN OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa.new
            cat ~/.ssh/id_rsa.bak >> ~/.ssh/id_rsa.new
            echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/id_rsa.new
            mv ~/.ssh/id_rsa.new ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "Fixed key format:"
            head -n 3 ~/.ssh/id_rsa
          else
            echo "SSH key has proper headers."
          fi

      - name: Test SSH connection with verbose output
        run: |
          echo "Testing SSH connection..."
          ssh -v -p 8022 -o BatchMode=yes -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@www295.onamae.ne.jp "echo SSH connection successful"

      - name: Deploy to GMO Cloud
        working-directory: service-site
        run: |
          echo "Starting deployment to www295.onamae.ne.jp:${{ secrets.REMOTE_PATH }}"
          rsync -avz -e "ssh -p 8022 -o StrictHostKeyChecking=no" --delete dist/ ${{ secrets.SSH_USERNAME }}@www295.onamae.ne.jp:${{ secrets.REMOTE_PATH }}
          echo "デプロイが完了しました！" 