name: Deploy to GMO Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'service-site/package-lock.json'

      - name: Debug - List directories
        run: |
          ls -la
          ls -la service-site || echo "service-site directory not found"

      - name: Install dependencies
        working-directory: service-site
        run: npm ci

      - name: Build project
        working-directory: service-site
        run: npm run build

      - name: Debug - Check build output
        working-directory: service-site
        run: |
          ls -la
          ls -la dist || echo "dist directory not found"

      - name: Debug SSH settings
        run: |
          echo "Checking SSH configuration..."
          echo "SSH_USERNAME is set: ${{ secrets.SSH_USERNAME != '' }}"
          echo "SSH_HOST is set: ${{ secrets.SSH_HOST != '' }}"
          echo "REMOTE_PATH is set: ${{ secrets.REMOTE_PATH != '' }}"
          echo "KNOWN_HOSTS is set: ${{ secrets.KNOWN_HOSTS != '' }}"
          echo "SSH_PRIVATE_KEY is set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
          echo "First few characters of SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY != '' && format('{0}...', secrets.SSH_PRIVATE_KEY, 0, 10) || 'Not provided' }}"

      # まったく新しい方法でSSHキーを生成
      - name: Generate new SSH keys
        run: |
          mkdir -p ~/.ssh
          
          # 既存の鍵の確認
          echo "Checking existing key content (first few chars):"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -c 20 || echo "No key content found"
          
          # ワークフロー内で新しい鍵を生成
          echo "Generating fresh SSH keys..."
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N "" -C "github-actions-deploy@example.com"
          
          # 公開鍵を表示
          echo "新しく生成された公開鍵（サーバーに設定する必要があります）:"
          cat ~/.ssh/id_rsa.pub
          
          # SSHディレクトリの権限を設定
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          
          # known_hostsファイルの設定
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
          # SSH設定の確認
          ls -la ~/.ssh

      # SSHの簡易テスト
      - name: Test SSH connection
        run: |
          # 実際のデプロイの前にSSH接続をテスト
          echo "Testing SSH connection (will fail because new key is not on server yet)..."
          ssh -v -p 8022 -o BatchMode=yes -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@www295.onamae.ne.jp "echo SSH connection successful" || echo "Expected failure - new key needs to be added to server"

      # スクリプトでのデプロイは一時的に無効化
      - name: Deployment instructions
        run: |
          echo "実際のデプロイのために、以下の作業が必要です:"
          echo "1. 上記に表示された新しい公開鍵をサーバーの ~/.ssh/authorized_keys に追加してください"
          echo "2. 追加したら、このワークフローを再実行してください"
          echo ""
          echo "※このワークフローは意図的に失敗するように設定されています。鍵のセットアップ後に再実行してください。"
          exit 1  # 意図的に失敗させる

      - name: Deploy to GMO Cloud
        working-directory: service-site
        run: |
          echo "Starting deployment to www295.onamae.ne.jp:${{ secrets.REMOTE_PATH }}"
          rsync -avz -e "ssh -p 8022 -o StrictHostKeyChecking=no" --delete dist/ ${{ secrets.SSH_USERNAME }}@www295.onamae.ne.jp:${{ secrets.REMOTE_PATH }}
          echo "デプロイが完了しました！" 